# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ocr_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ocr_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ocr_service.proto\x12\x03ocr\"V\n\nOCRRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0c\n\x04side\x18\x03 \x01(\t\x12\x15\n\rthinking_mode\x18\x04 \x01(\x08\"W\n\x0bOCRResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08raw_text\x18\x02 \x01(\t\x12\x16\n\x0e\x65xtracted_data\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t2>\n\nOCRService\x12\x30\n\x0b\x45xtractData\x12\x0f.ocr.OCRRequest\x1a\x10.ocr.OCRResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OCRREQUEST']._serialized_start=26
  _globals['_OCRREQUEST']._serialized_end=112
  _globals['_OCRRESPONSE']._serialized_start=114
  _globals['_OCRRESPONSE']._serialized_end=201
  _globals['_OCRSERVICE']._serialized_start=203
  _globals['_OCRSERVICE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
